name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened]

jobs:
  claude-response:
    # Only run if comment contains @claude and is from @snowmead
    if: |
      github.event.pull_request.user.login == 'snowmead'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history for better context
          fetch-depth: 0

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          # Required: Anthropic API key stored in repository secrets
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # GitHub token for API access (automatically provided)
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Customize the trigger phrase (default is @claude)
          trigger_phrase: "@claude"

          # Allow all necessary tools for PR management and code changes
          allowed_tools: "Task,Bash,Glob,Grep,LS,Read,Edit,MultiEdit,Write,NotebookRead,NotebookEdit,TodoRead,TodoWrite"

          # Custom instructions for handling change units and PR workflows
          custom_instructions: |
            <role>
            You are a GitHub workflow assistant that creates sub-branches and PRs for change units. You MUST create a sub-branch and sub-PR for EACH change unit.
            </role>

            <workflow>
            <step1>
            Store the EXACT trigger comment text (needed for sub-PRs)
            </step1>

            <step2>
            Read PR description and identify ALL change units needing implementation
            </step2>

            <step3>
            For EACH change unit:

            <create_branch>
            - Create branch from CURRENT PR branch (NOT main)
            - Name: "feature/[change-unit-description]"
            - Switch to new branch
            </create_branch>

            <analyze>
            Generate analysis with:
            - Overview of changes needed
            - List of affected files
            - Implementation approach
            - Key considerations/risks
            </analyze>

            <create_pr>
            Create PR with:
            - Target: Parent PR branch (NOT main)
            - Title: "Change Unit: [description]"
            - Body: Analysis + task checklist + parent PR reference
            </create_pr>

            <add_comment>
            Add comment to new PR:
            ```
            [Original trigger comment]

            ---

            **Task:** Complete the task list in the PR description above.
            ```
            </add_comment>

            <update_parent>
            Update parent PR description with:
            - Links to new branch and PR
            - Fixed file links
            - Status tracking
            </update_parent>
            </step3>
            </workflow>

            <critical_rules>
            - ALWAYS create sub-branches from parent PR branch
            - NEVER target main/master with sub-PRs
            - MUST preserve exact trigger comment in each sub-PR
            - STOP and report if branch/PR creation fails
            </critical_rules>

          # Set maximum number of turns for complex operations
          # max_turns: 25

          # Set timeout in minutes (default: 30)
          timeout_minutes: 30

          # Optional: Specify a different model
          # model: "claude-3-5-sonnet-latest"
